baseURL = "http://example.org/"
languageCode = "en-us"
title = "PyTutorials"
publishDir = "docs"
theme = "casper"
staticDir = ["images"]
Copyright = "All rights reserved - 2018"
canonifyurls = true
paginate = 1

[Params]
  description = "Learn python by practice"
  twitterName = "adnan"
  facebookName = "adnan"
  instagramName = "adnan"
  readingTime = true
  website = "fas"
  logo = "/images/logo.png"
  cover = "/images/cover.jpg"
  image = "/images/coversad.jpg"
  pages = 5
  author = "Adnan"
  authorlocation = "Grenoble, France"
  authorwebsite = "https://www.logorain.com"
  hideHUGOSupport = true
  
[[menu.main]]
  name = "Home"
  url = "/home/"
  weight = 3
  
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 1
  
[permalinks]
  post = "/:slug/"
[sitemap]
  ChangeFreq = ""
  Filename = "sitemap.xml"
  Priority = "-1"