baseURL = "https://3adnank.github.io/pytutorials/"
languageCode = "en-us"
title = "PyTutorials"
publishDir = "docs"
themesDir = "themes"
theme = "casper"
staticDir = ["images"]
Copyright = "All rights reserved - 2018"
canonifyurls = true
paginate = 1

[Params]
  description = "Learn python by doing"
  twitterName = "adnankandar"
  instagramName = "adnankandar"
  github = "3adnank"
  readingTime = true
  website = "fas"
  logo = "https://3adnank.github.io/pytutorials/images/logo.png"
  cover = "https://3adnank.github.io/pytutorials/images/cover.jpg"
  image = "https://3adnank.github.io/pytutorials/images/cover.jpg"
  pages = 5
  author = "Adnan"
  #authorlocation = "Grenoble, France"
  authorwebsite = "https://www.logorain.com"
  hideHUGOSupport = true
  
[[menu.main]]
  name = "Home"
  url = "/home/"
  weight = 3
  
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 1
  
[permalinks]
  post = "/:slug/"
[sitemap]
  ChangeFreq = ""
  Filename = "sitemap.xml"
  Priority = "-1"