baseURL = "https://3adnank.github.io/pytutorials/"
languageCode = "en-us"
title = "PyTutorials"
publishDir = "docs"
themesDir = "themes"
theme = "casper"
staticDir = ["images"]
Copyright = "All rights reserved - 2018"
canonifyurls = true
paginate = 10
DisqusShortname = "https-3adnank-github-io-pytutorials"

[Params]
  description = "Learn python by doing"
  twitterName = "adnankandar"
  instagramName = "adnankandar"
  githubName = "3adnank"
  readingTime = true
  comments = true
  website = "https://www.logorain.com"
  logo = "https://3adnank.github.io/pytutorials/images/logo.png"
  cover = "https://3adnank.github.io/pytutorials/images/cover.jpg"
  image = "https://3adnank.github.io/pytutorials/images/cover.jpg"
  #pages = 5
  googleAnalyticsUserID = "UA-120319729-1"
  author = "Adnan"
  #authorlocation = "Grenoble, France"
  authorwebsite = "https://www.logorain.com"
  hideHUGOSupport = true
  
[permalinks]
  post = "/:slug/"
[sitemap]
  ChangeFreq = ""
  Filename = "sitemap.xml"
  Priority = "-1"
